name: Integracion Continua con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  test-doc-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias pytest y pdoc
        run: pip install pytest pdoc

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests"
          file_pattern: README.md

      - name: Crear carpeta documentacion si no existe
        run: mkdir -p ./documentacion

      - name: Ejecutar pdoc para generar la documentación
        run: pdoc update_readme.py -o ./documentacion

      - name: Añadir documentación generada al índice git
        run: git add documentacion/**

      - name: Commit automático de documentación generada
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizando la documentación de pdoc"
          file_pattern: documentacion/**

     
