name: Integracion Continua con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pytest

      - name : Instalar Pydoc
        run : pip install pdoc

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name : Ejecutar el script para documentar la clase update_readme.py y lo almacena en la carpeta de documentacion
        run : pdoc update_readme.py -o ./documentacion

      - name: Commit automático del README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests"
          file_pattern: README.md