name: Integracion Continua con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  test-doc-update:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Instalacion de las dependencias 
      - name: Instalar dependencias pytest y pdoc
        run: pip install pytest pdoc

      # Script a la hora de ejecucion de las pruebas del update_readme
      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests"
          file_pattern: README.md

      # Creacion de los documentos en Pdoc en formato HTML 
      - name: Crear carpeta documentacion si no existe
        run: mkdir -p ./documentacion

      - name: Ejecutar pdoc para generar la documentacion en formato HTML 
        run: pdoc update_readme.py -o ./documentacion

      - name: Añadir documentacion generada al índice git
        run: git add documentacion/**

      - name: Commit automatico de documentacion generada
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizando la documentacion de pdoc"
          file_pattern: documentacion/**

      # Creacion de los documentos en formato Markdown con Pandoc
      - name: Instalar pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convertir HTML a Markdown con pandoc
        run: |
          pandoc -f html -t markdown documentacion/update_readme.html -o documentacion/documentacion.md

      - name: Añadir documentacion Markdown al índice git
        run: git add documentacion/**

      - name: Commit automático de documentacion Markdown
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizando documentacion Markdown convertida con pandoc"
          file_pattern: documentacion/**


  
     
