name: Integracion Continua con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Instalar Pydoc
        run: pip install pdoc

      - name: Crear carpeta documentacion si no existe
        run: mkdir -p ./documentacion

      - name: Ejecutar el script para documentar la clase update_readme.py y almacenar la documentacion
        run: pdoc update_readme.py -o ./documentacion

      - name: Añadir documentación generada al índice git
        run: git add ./documentacion

      - name: Commit automático del README y documentacion
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests y generacion de la documentacion"
          file_pattern: |
            README.md
            documentacion/**
