name: Integracion Continua con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install pytest pdoc

      - name: Crear carpeta documentacion si no existe
        run: mkdir -p ./documentacion

      - name: Ejecutar pdoc para generar la documentaci칩n
        run: pdoc update_readme.py -o ./documentacion

      - name: A침iadiendo el readme y los documentos de la carpeta documentacion en el staged area
        run: git add README.md documentacion/**


      - name: Commit autom치tico de README y documentaci칩n
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests y generacion de la documentacion"
          file_pattern: |
            README.md
            documentacion/**
